Add Loader Delay to Group Search
alphawolfteam/friends-client pull request #22
Opened 2021-05-10 11:25 UTC by PCOffline

2021-05-10 15:24 UTC, carmeltsadok requested changes
Great job!!

2021-05-10 15:24 UTC, carmeltsadok commented on mock-api/app.js
> +app.use(express.json({ limit: '50mb' }));
Why?

2021-05-10 15:24 UTC, carmeltsadok commented on src/components/search-group/scrollable-groups-result/ScrollableGroupsResult.jsx
> +          {publicGroups?.length && publicGroupsList}
```suggestion
          {currentUserGroups?.length > 0 && currentUserGroupsList}
          {privateGroups?.length > 0 && privateGroupsList}
          {publicGroups?.length > 0 && publicGroupsList}
```

If you search only `מבצע סודי` for example, you will get `0` on public groups (and it shows it)

2021-05-10 15:24 UTC, carmeltsadok commented on src/components/search-group/scrollable-groups-result/ScrollableGroupsResult.jsx
> +  useEffect(() => () => clearTimeout(timeout));
When does it happen?

2021-05-10 15:24 UTC, carmeltsadok commented on src/components/search-group/scrollable-groups-result/ScrollableGroupsResult.jsx
> +    }, 1000);
I think it should be inside an `useEffect` method.

2021-05-11 11:27 UTC, PCOffline commented
FYI: In my opinion the 1 second delay causes certain confusion and an illusion of lag in the app, I suggest decreasing the delay.

2021-05-12 07:02 UTC, carmeltsadok approved these changes

2021-05-12 07:04 UTC, carmeltsadok commented
Great job. I would like you not to resolve messages. I prefer liking a message because I can't remember what I have said :)

2021-05-12 07:21 UTC, merged