Add Group Search
alphawolfteam/friends-client pull request #23
Opened 2021-05-19 10:18 UTC by PCOffline

2021-05-19 10:22 UTC, PCOffline commented
One problem is that the auto-complete now pushes the list down. I had to adjust the positions of the search-bar to not be absolute and that's a side-effect. Will work on that soon

2021-05-19 12:09 UTC, PCOffline commented
Should there be an icon in the search bar of a group that the user cannot edit?

2021-05-20 13:48 UTC, carmeltsadok requested changes

2021-05-20 13:48 UTC, carmeltsadok commented on src/components/shared/users-input-fields/UsersInputFields.jsx
> +          className={classes.inputField}
It doesn't affect the component

2021-05-26 08:22 UTC, carmeltsadok requested changes

2021-05-26 08:22 UTC, carmeltsadok commented on src/components/shared/users-input-fields/UsersInputFields.jsx
> +        </IconButton>
```suggestion
           <Fade
            in
            mountOnEnter
            unmountOnExit
            exit={false}
            timeout={500}
          >
            {isModeSearch
              ? (
                <Tooltip title={t('tooltip.search')}>
                  <SearchIcon />
                </Tooltip>
              )
              : (
                <Tooltip title={t('tooltip.add')}>
                  <AddIcon />
                </Tooltip>
              )}
          </Fade>
```

2021-05-26 08:22 UTC, carmeltsadok commented on src/components/shared/users-input-fields/UsersInputFields.styles.js
> +    flexDirection: 'row',
its row by default

2021-05-26 08:22 UTC, carmeltsadok commented on src/components/shared/users-input-fields/UsersInputFields.jsx
> +    updatedUsersList.length > 0 ? sortedUsers.map(({ user, role }) => (
We need to change the `message.noMembersFound` when there are users in the group, but just there are no search results.

2021-05-26 08:22 UTC, carmeltsadok commented on src/components/shared/users-input-fields/UsersInputFields.jsx
> +        </IconButton>
And you haven't changed the order of the buttons :)

2021-05-26 09:01 UTC, PCOffline commented on src/components/shared/users-input-fields/UsersInputFields.jsx
> +        </IconButton>
What do you mean?

2021-05-27 11:38 UTC, carmeltsadok requested changes

2021-05-27 11:38 UTC, carmeltsadok commented on src/components/shared/users-input-fields/UsersInputFields.jsx
> +    updatedUsersList.length > 0 ? sortedUsers.map(({ user, role }) => (
Have you done it?

2021-05-27 13:06 UTC, merged