Dev
alphawolfteam/friends-client pull request #8
Opened 2021-01-14 15:50 UTC by carmeltsadok

2021-01-20 08:56 UTC, lustigy96 requested changes

2021-01-20 08:56 UTC, lustigy96 commented on src/services/GroupsService.js
> +    return role;
Is it possible that the user won't be in that group? 

use map + find instead of 'if' in a loop: 

groupUsersIds =  group.users.map((groupUser) => groupUser.id)  //not sure about this syntax
then: 
groupUserIds.find(userId) 
and so on...

2021-01-20 08:56 UTC, lustigy96 commented on src/services/GroupsService.js
> +    return userRole;
Is it possible that the user won't be in that group?

use map + find instead of 'if' in a loop:

groupUsersIds = group.users.map((groupUser) => groupUser.id) //not sure about this syntax
then:
groupUserIds.find(userId)
and so on...

2021-01-20 08:56 UTC, lustigy96 commented on src/services/GroupsService.js
> +  }
```suggestion
    static getUserGroups = async (userId) => {
    return await axios.get(`${config.uri.api_gateway_uri}api/users/${userId}/groups`,
      { ...headers });
  }
```

2021-01-20 08:56 UTC, lustigy96 commented on src/services/GroupsService.js
> +
take a look at the remark of getUserGroups function and to the same in here :)

2021-01-20 08:56 UTC, lustigy96 commented on src/services/GroupsService.js
> +  }
take a look at the remark of getUserGroups function and to the same in here :)

2021-01-20 08:56 UTC, lustigy96 commented on src/services/UsersService.js
> +
no reason for global variable

2021-01-20 08:56 UTC, lustigy96 commented on src/services/UsersService.js
> +
```suggestion
  static searchUsers = async (searchValue) => {
    return { data } = await axios.get(`${config.uri.api_gateway_uri}api/users`,
      { params: { partialName: searchValue } },
      { ...headers });
  }
}

```

2021-01-20 08:56 UTC, lustigy96 commented on src/services/ValidationService.js
> +  }
```suggestion
  static validateGroupObject = (groupObject, minGroupNameLength) => {
    [
      this.validateGroupName(groupObject.name, minGroupNameLength),
      this.validateGroupDescription(groupObject.description),
      this.validateGroupUsers(groupObject.users),
    ].filter((field) => field !== null);
  }
```

2021-01-20 08:56 UTC, lustigy96 commented on src/services/ValidationService.js
> +
```suggestion
  static validateGroupDescription = (groupDescription) => {
    !groupDescription || groupDescription === '' ? 'emptyDescriptionInput' : null;
  }


```

2021-01-20 08:56 UTC, lustigy96 commented on src/services/ValidationService.js
> +  }
look at validateGroupDescription function and do the same :)

2021-01-21 07:13 UTC, carmeltsadok commented on src/index.js
>  import React from 'react';
1. The only difference between the groups is that if it is public- everybody can see it, otherwise- only the members.
How do you think we should explain it in the UI?

2. I decided to divide the files into features- every feature has its own index file and its own components directories. 
Also, there are shared components that are used in more than one feature. Before I divided it like that, There were a lot of directories and it was very messy. What do you think about it? @yonatandt  @yubbi99 

And yes, I will be doing those things next time. There were a lot of changes during my work on the API itself, and therefore on the client.

2021-01-21 07:24 UTC, carmeltsadok commented on src/components/search-group/group-search-bar/GroupSearchBar.jsx
> +        <Search />
The group search button enables you to search when the length is not even. 
We decided to force a search every two chars.
Because the name's length and tag's length is at least 2 chars, we don't want to enable to search for less than that- it will be showing too many options. 
If it is less than that- the user sees all of the groups he is in- so the search will be rare, as long as the user doesn't need to search for another public group or that he doesn't have a lot of groups.

2021-01-21 07:43 UTC, carmeltsadok commented on src/services/UsersService.js
> +
It won't be working. [https://javascriptweblog.wordpress.com/2015/11/02/of-classes-and-arrow-functions-a-cautionary-tale/](url)

2021-01-21 07:45 UTC, carmeltsadok commented on src/services/ValidationService.js
> +  }
It won't be working. [https://javascriptweblog.wordpress.com/2015/11/02/of-classes-and-arrow-functions-a-cautionary-tale/](url) The replacement of the return either.

2021-01-21 07:47 UTC, carmeltsadok commented on src/services/ValidationService.js
> +
Changed to:
```suggestion
  static validateGroupDescription(groupDescription) {
    return !groupDescription || groupDescription === '' ? 'emptyDescriptionInput' : null;
  }
```

2021-01-21 07:48 UTC, carmeltsadok commented on src/services/ValidationService.js
> +  }
Changed to: 
```suggestion
  static validateGroupUsers(groupUsers) {
    return !groupUsers || groupUsers.length <= 1 ? 'noMembersInList' : null;
  }
```

2021-01-21 07:50 UTC, carmeltsadok commented on src/services/UsersService.js
> +
Also, return statement should not contain assignment according to eslint roles.

2021-01-21 08:13 UTC, carmeltsadok commented on src/index.js
> +const globalTheme = createMuiTheme({
I created a theme file.

2021-01-21 08:13 UTC, carmeltsadok commented on src/index.js
> +      },
I created a theme file.

2021-01-26 14:39 UTC, lustigy96 commented on src/index.js
>  import React from 'react';
1. The explanation of private\public group might be "Only group's members will see that group" and "This group can be viewed by everyone" 
2. I still think my way, except the shared directory, which I think its fine :) @yonatandt  @yubbi99,

2021-01-26 14:42 UTC, lustigy96 commented on src/components/search-group/group-search-bar/GroupSearchBar.jsx
> +        <Search />
Well that is cool, but didn't work for me :O 
If that's the case so its fine, just need to be checked again (we can see that together)

2021-03-10 15:06 UTC, lustigy96 approved these changes

2021-03-10 15:20 UTC, merged